#!/bin/bash

cleanup() {
    echo "Container stopped, performing cleanup..."
    bash $VS_SERVER_PATH/server.sh stop
}

if [ ! -f $VS_SERVER_PATH/server.sh ]; then
    echo "Server runtime is missing. Download server with use 'sudo docker exec vintage_story_server bash -c \"vs_update <url_to_download_server.tar.gz>'\""
    echo "and restart container"

    # check if $VS_SERVER_DOWNLOAD_URL is set
    if [ -z "$VS_SERVER_DOWNLOAD_URL" ]; then
        echo "No download url provided. Please set the VS_SERVER_DOWNLOAD_URL environment variable."
    
    else
        echo "Downloading server from container env variables..."
        bash vs_update $VS_SERVER_DOWNLOAD_URL
        echo "Server downloaded. Restarting container..."
        exit 0
    fi

    sleep infinity & wait
else

    trap 'true' SIGTERM
    
    supercronic ~/crontab &
  
    bash vs_server start
    
    sleep infinity &
    
    wait
    
    cleanup
fi
