apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: vintage-story
namespace: vintage-story
resources:
  - vs-secret.yaml # This is the secret that will be used to pull the image from the private registry
  - vs-configmap.yaml
  - vs-service.yaml
  - vs-pvc.yaml
  - vs-statefulset.yaml # This is the StatefulSet that will run the Vintage Story server, with the image pulled from the private registry
  - filebrowser-ingress.yaml # This is the Ingress that will expose the Filebrowser service 
commonLabels:
  app: vintage-story
# This is the image that will be pulled from the private registry
images:
  - name: vintage-story-server
    newName: core.harbor.k.gallis.cloud/gallis/vintage_story
    newTag: latest
  - name: vintage-story-filebrowser
    newName: core.harbor.k.gallis.cloud/dockerhub-proxy/hurlenko/filebrowser
    newTag: latest
