apiVersion: v1
kind: ConfigMap
metadata:
  name: vs-config
data:
  TZ: "America/Los_Angeles"
  VS_SERVER_DOWNLOAD_URL: "https://cdn.vintagestory.at/gamefiles/stable/vs_server_linux-x64_1.19.8.tar.gz"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vs-filebrowser-config
data:
  filebrowser.json: |-
    {
      "port": 80,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database/filebrowser.db",
      "root": "/srv"
    }