apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
metadata:
  name: vs-filebrowser-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi