---
apiVersion: v1
kind: Service
metadata:
  name: vintage-story-server
spec:
  selector:
    app: vintage-story-server
  ports:
    - protocol: TCP
      port: 42420
      targetPort: 42420
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: vintage-story-filebrowser
spec:
  selector:
    app: vintage-story-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  