---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-k3s-secret
spec:
  secretStoreRef:
    name: vault-west
    kind: ClusterSecretStore
  target:
    name: harbor-k3s
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: kubernetes/docker-common
      property: harbor-k3s-gw-dockerconfig.json