apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vintage-story-server
spec:
  serviceName: "vintage-story-server"
  replicas: 1
  selector:
    matchLabels:
      app: vintage-story-server
  template:
    metadata:
      labels:
        app: vintage-story-server
    spec:
      imagePullSecrets:
        - name: harbor-k3s
      initContainers:
      - name: init-chown-data
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /var/vintage_story", "chown -R 1000:1000 /database", "chown -R 1000:1000 /config"]
        volumeMounts:
        - name: vs-data
          mountPath: /var/vintage_story
        - name: vs-filebrowser-db
          mountPath: /database
          subPath: db
        - name: vs-filebrowser-db
          mountPath: /config
          subPath: config
      containers:
      - name: vintage-story-server
        image: vintage-story-server:latest  # You'll need to replace this with the actual image
        imagePullPolicy: Always
        ports:
        - name: vs-server
          containerPort: 42420
        envFrom:
        - configMapRef:
            name: vs-config
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: vs-data
          mountPath: /var/vintage_story
      - name: vintage-story-filebrowser
        image: filebrowser/filebrowser:s6
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
        - name: filebrowser
          containerPort: 80 
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000    
        volumeMounts:
        - name: vs-data
          mountPath: /srv
        - name: vs-filebrowser-db
          mountPath: /database
          subPath: db
        - name: vs-filebrowser-db
          mountPath: /config
          subPath: config
      volumes:
      - name: vs-data
        persistentVolumeClaim:
          claimName: vs-pvc
      - name: vs-filebrowser-db
        persistentVolumeClaim:
          claimName: vs-filebrowser-db-pvc