name: Docker Image CI

on:
  push:
    branches: [ "any_net_7" ]
  pull_request:
    branches: [ "any_net_7" ]
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      name: Checkout Repo Code

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REPOSITORY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host      

    - name: Prepare Scrips
      run:  bash ./prepare.sh
      working-directory: ./src 

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY }}/${{ secrets.DOCKER_LIBRARY }}/${{ vars.IMAGE_NAME }}:latest
       
    - uses: 8398a7/action-slack@v3
      name: Slack Notification
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
